version: '3'

services:
  web:
    build: ./
    environment:
      - APACHE_RUN_USER=#1000
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./:/var/www/html
    ports:
      - 8115:80
    working_dir: /var/www/html

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddu10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 9115:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=64M
    depends_on:
      - db
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379